# Application configuration

report:
  excluded_projects: [Personal, Timeless, "Career & Network", Someday, Routines, "Weekly Review"]

todoist:
   token: "5b41f0e89138743efd5f71b554d119d561b6eeda"
   weekly-label: "This-Week"
   waiting-label: "Waiting"
   weekly-review: "Weekly Review"
   excluded-upcoming-projects: [Routines, "Weekly Review"]

github:
  token: "c93145173d593174729cb72a4d74d7af42716525"
  projects:
    - eclipse-vertx/vert.x
    - quarkusio/quarkus
    - quarkusio/quarkus-images
    - smallrye/smallrye-mutiny
    - smallrye/smallrye-reactive-streams-operators
    - smallrye/smallrye-reactive-messaging
    - smallrye/smallrye-context-propagation
    - vert-x3/vertx-amqp-client
    - eclipse/microprofile-reactive-streams-operators
    - eclipse/microprofile-reactive-messaging
  username: cescoffier

pocket:
  consumer-key: "57479-e7678a40906f0cf20b3ab989"
  access-token: "f0d38067-c6cc-0ac1-5959-518ad1"

# Quarkus configuration
quarkus:
  http:
    port: 9876
  banner:
     enabled: false
  # Jandex
  index-dependency:
    gmail:
      group-id: com.google.apis
      artifact-id: google-api-services-gmail
    google-api-client:
      group-id: com.google.api-client
      artifact-id: google-api-client
    google-http-client:
      group-id: com.google.http-client
      artifact-id: google-http-client
    opencensus-api:
      group-id: io.opencensus
      artifact-id: opencensus-api